name: 

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3   
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven   
      - name: Build with Maven
        run: mvn clean package
      - name: Run tests with Maven
        run: mvn test
      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: todo-artifact
          path: .  
      - name: Deployment
        uses: Azure/webapps-deploy@v3.0.0
        with:
           app-name: 'to-do-app01010'
           publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE}}

      - name: Download artifact
        uses: actions/download-artifact@v2.1.1
        with:
          name: todo-artifact
        


